# Generated by scripts/generate-flake.py from entries/*.nix.
# Edit the entry files and regenerate this file; do not edit declarations here.
{
  description = "Melorise Nix Packages Repository";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    "amber-pm" = {
      "url" = "git+https://gitee.com/Melorise/amber-pm.git?ref=nixos";
    };
    "clash-party" = {
      "url" = "git+https://github.com/Melorise/cp-nix.git?ref=main";
    };
    "codex-desktop" = {
      "url" = "git+https://github.com/Melorise/codex-desktop-linux-builder.git?ref=nix";
    };
    "spark-store" = {
      "flake" = false;
      "url" = "git+https://gitee.com/Melorise/spark-store.git?ref=nixos";
    };
  };

  nixConfig = {
    extra-substituters = [
      "https://melorise-cp-nix.cachix.org"
      "https://codex-desktop-linux.cachix.org"
    ];
    extra-trusted-public-keys = [
      "melorise-cp-nix.cachix.org-1:GNg96VizkktTdGMrvl6+PLPHY3jPce4a72HqP2cj4S4="
      "codex-desktop-linux.cachix.org-1:nX/xy6AdK9hQE24A8ALGjkCKj2ObFmcnemiL5Cid4nk="
    ];
  };

  outputs =
    inputs:
    import ./lib/mk-outputs.nix {
      inherit inputs;
      entries = import ./entries;
    };
}
