#!/usr/bin/env python3
"""Generate the literal flake input and cache declarations from MNPR entries."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
FLAKE_PATH = ROOT / "flake.nix"
CATALOG_EXPR = ROOT / "scripts" / "catalog-json.nix"


def nix_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def nix_value(value: Any, indent: int = 0) -> str:
    prefix = " " * indent
    child_prefix = " " * (indent + 2)

    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return nix_string(value)
    if isinstance(value, list):
        if not value:
            return "[ ]"
        body = "\n".join(f"{child_prefix}{nix_value(item, indent + 2)}" for item in value)
        return f"[\n{body}\n{prefix}]"
    if isinstance(value, dict):
        if not value:
            return "{ }"
        body = "\n".join(
            f"{child_prefix}{nix_string(key)} = {nix_value(item, indent + 2)};"
            for key, item in sorted(value.items())
        )
        return f"{{\n{body}\n{prefix}}}"
    raise TypeError(f"Unsupported catalog value: {value!r}")


def load_catalog() -> dict[str, dict[str, Any]]:
    result = subprocess.run(
        [
            "nix",
            "eval",
            "--json",
            "--file",
            str(CATALOG_EXPR),
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    catalog = json.loads(result.stdout)
    if not isinstance(catalog, dict):
        raise TypeError("MNPR catalog must evaluate to an attribute set")
    return catalog


def unique_caches(catalog: dict[str, dict[str, Any]]) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()

    for name in sorted(catalog):
        for cache in catalog[name].get("caches", []):
            pair = (cache["substituter"], cache["publicKey"])
            if pair not in seen:
                seen.add(pair)
                result.append(cache)
    return result


def render(catalog: dict[str, dict[str, Any]]) -> str:
    input_lines = [
        '    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";',
    ]
    for name in sorted(catalog):
        input_lines.append(
            f"    {nix_string(name)} = {nix_value(catalog[name]['source'], 4)};"
        )

    caches = unique_caches(catalog)
    substituters = nix_value([cache["substituter"] for cache in caches], 4)
    public_keys = nix_value([cache["publicKey"] for cache in caches], 4)

    return f'''# Generated by scripts/generate-flake.py from entries/*.nix.
# Edit the entry files and regenerate this file; do not edit declarations here.
{{
  description = "Melorise Nix Packages Repository";

  inputs = {{
{chr(10).join(input_lines)}
  }};

  nixConfig = {{
    extra-substituters = {substituters};
    extra-trusted-public-keys = {public_keys};
  }};

  outputs =
    inputs:
    import ./lib/mk-outputs.nix {{
      inherit inputs;
      entries = import ./entries;
    }};
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when flake.nix is not synchronized with entries",
    )
    args = parser.parse_args()

    generated = render(load_catalog())

    if args.check:
        current = FLAKE_PATH.read_text() if FLAKE_PATH.exists() else ""
        if current != generated:
            print(
                "flake.nix is out of date; run scripts/generate-flake.py",
                file=sys.stderr,
            )
            return 1
        print("flake.nix is synchronized with entries")
        return 0

    FLAKE_PATH.write_text(generated)
    print(f"generated {FLAKE_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
